<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ChromeDriverService</name>
   <tag></tag>
   <elementGuidId>3f9f1da3-75f1-4cd8-a41a-3199af35e4a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'ChromeDriverService')])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>dd > a[title=&quot;class in org.openqa.selenium.chrome&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8f4ceb5c-7689-4d87-affe-fe7e40be5873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>ChromeDriverService.html</value>
      <webElementGuid>26d2b442-954b-4a48-bb28-af3264919ac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>class in org.openqa.selenium.chrome</value>
      <webElementGuid>6d98c7d9-c92d-4083-a872-b30adf90c3b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ChromeDriverService</value>
      <webElementGuid>2a7b02ee-30c9-4592-9663-020804641f10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;contentContainer&quot;]/div[@class=&quot;description&quot;]/ul[@class=&quot;blockList&quot;]/li[@class=&quot;blockList&quot;]/dl[1]/dd[1]/a[1]</value>
      <webElementGuid>7cbd0b7f-4523-4bc5-b5e3-2f2175044c23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ChromeDriverService.Builder/iframe_classFrame</value>
      <webElementGuid>bdbe8280-8b07-4b95-8329-fdd89fa66d38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'ChromeDriverService')])[3]</value>
      <webElementGuid>b4b260a7-2055-4052-85d4-076f313b8cad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enclosing class:'])[1]/following::a[1]</value>
      <webElementGuid>aa980104-c801-40cd-8f42-deb3cc38933e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='org.openqa.selenium.chrome.ChromeDriverService.Builder'])[1]/following::a[1]</value>
      <webElementGuid>a5fdd355-ee0b-4ebe-bb8c-11daeb404ea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Builder.class'])[1]/preceding::a[1]</value>
      <webElementGuid>6ce0e7d5-a9eb-483d-aa5f-e8716ef22b71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'ChromeDriverService.html')])[2]</value>
      <webElementGuid>42a4137b-290e-4225-a8cf-c915a2445890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//dd/a</value>
      <webElementGuid>d7decda9-e9ea-474c-96b2-2a47e354ef02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'ChromeDriverService.html' and @title = 'class in org.openqa.selenium.chrome' and (text() = 'ChromeDriverService' or . = 'ChromeDriverService')]</value>
      <webElementGuid>84457060-47f9-4c1a-9908-452825db8a62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
