<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_UsernameAndPassword</name>
   <tag></tag>
   <elementGuidId>2eaeff52-4af5-419b-9588-b2655b8be785</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'UsernameAndPassword')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;class in org.openqa.selenium&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a5ce5284-b58c-46c7-8f44-fd50722a8afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>UsernameAndPassword.html</value>
      <webElementGuid>b7e6a3a7-a2ca-4ec7-ab79-2aa15f20153a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>class in org.openqa.selenium</value>
      <webElementGuid>c94038d4-5d0c-456c-9288-7e159c26d6a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>UsernameAndPassword</value>
      <webElementGuid>0f093de0-a1b1-48d5-995e-8b92d45386ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;contentContainer&quot;]/div[@class=&quot;description&quot;]/ul[@class=&quot;blockList&quot;]/li[@class=&quot;blockList&quot;]/dl[1]/dd[1]/code[1]/a[1]</value>
      <webElementGuid>73446c42-b105-4bb9-b707-b8b7a108e9ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Credentials/iframe_classFrame</value>
      <webElementGuid>fcce5f7b-85ce-4104-b012-d22bd69dcd16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'UsernameAndPassword')]</value>
      <webElementGuid>cf0be171-8cee-48ec-aa5b-af4496a221c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Known Implementing Classes:'])[1]/following::a[1]</value>
      <webElementGuid>349b3dc2-4d29-49e9-8930-6a3787260ee2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Interface Credentials'])[1]/following::a[1]</value>
      <webElementGuid>da0a4827-83bb-49d6-b09f-071ed1b017b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credentials'])[2]/preceding::a[1]</value>
      <webElementGuid>462e880d-bb7b-4f7a-940f-b78b0ce09041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='UsernameAndPassword']/parent::*</value>
      <webElementGuid>1ebb8dc4-fd71-483c-b1e5-4a7c3946e2a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'UsernameAndPassword.html')]</value>
      <webElementGuid>38a88548-9921-4148-9c36-87df458f2e3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//code/a</value>
      <webElementGuid>8ba424de-d06f-4a6b-8572-d7358faabc8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'UsernameAndPassword.html' and @title = 'class in org.openqa.selenium' and (text() = 'UsernameAndPassword' or . = 'UsernameAndPassword')]</value>
      <webElementGuid>720ec348-d16a-43aa-b7a1-30c3c76c9419</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
