<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ChromeDriverService.Builder</name>
   <tag></tag>
   <elementGuidId>22c2ff1d-2040-47e1-8bd8-08fe0e87d708</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'ChromeDriverService.Builder')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7dcb17f2-0a06-4874-a8ae-dcb6484ba2a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>ChromeDriverService.Builder.html</value>
      <webElementGuid>2e46066d-8489-4e89-a60a-d75e0b8c6659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>class in org.openqa.selenium.chrome</value>
      <webElementGuid>81adbb74-633f-42b7-92e0-3e61d0d53a8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>classFrame</value>
      <webElementGuid>53b5f5c2-8f20-4684-9239-fb4785fac728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ChromeDriverService.Builder</value>
      <webElementGuid>95a9ea66-0426-4f1d-837c-7d6ead83deb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;indexContainer&quot;]/section[1]/ul[1]/li[6]/a[1]</value>
      <webElementGuid>bee6bb91-7bc9-4115-9d7b-b1027302b6f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_UsernameAndPassword/iframe_packageFrame</value>
      <webElementGuid>5072e8a4-83fd-4aa6-877a-f1525d6a8fec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ChromeDriverService.Builder')]</value>
      <webElementGuid>70467da3-0006-4f12-b63f-a6c6ef636022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ChromeDriverService'])[1]/following::a[1]</value>
      <webElementGuid>3e66ab04-54a6-42ad-a4df-531b0955532f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ChromeDriverInfo'])[1]/following::a[2]</value>
      <webElementGuid>5690190a-e385-4fcf-a1f9-487be58609fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ChromeOptions'])[1]/preceding::a[1]</value>
      <webElementGuid>8eb192a8-3e88-4635-8e5d-1563eda4e7bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enums'])[1]/preceding::a[2]</value>
      <webElementGuid>b6f104e1-f4f3-4a7f-b3cf-8ab138ca7a7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ChromeDriverService.Builder']/parent::*</value>
      <webElementGuid>0da313fb-b612-413b-a2ce-a2deafb2711b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'ChromeDriverService.Builder.html')]</value>
      <webElementGuid>b1918d3b-b921-4598-9841-18cf695af0d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>dcf4a057-e1b3-40a2-8d39-b1889435d3cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'ChromeDriverService.Builder.html' and @title = 'class in org.openqa.selenium.chrome' and (text() = 'ChromeDriverService.Builder' or . = 'ChromeDriverService.Builder')]</value>
      <webElementGuid>c486e88c-73f9-440a-aaa6-b7922e91b76b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
